export function buildSeoPrompt(report : any) : string{

    const prompt = 
    `
        You are an experienced Technical SEO Consultant.

        The following audit was generated by an automated rule engine.

        Do NOT invent new issues.

        Only explain the issues provided.

        Generate JSON only.

        ${report}
        
        Respond ONLY as JSON.
    `
    return prompt;
}