export function buildSeoPrompt(report : any) : string{

    const reportString = typeof report == 'string' ? report : JSON.stringify(report,null,2);

    console.log(reportString)

    const prompt = 
    `
        You are an experienced Technical SEO Consultant.

        Your task is to explain the findings produced by an automated SEO rule engine.

        IMPORTANT RULES

        1. The rule engine is the ONLY source of truth.
        2. NEVER invent new SEO issues.
        3. NEVER estimate or calculate values.
        4. NEVER assume missing information.
        5. NEVER mention anything that is not explicitly present in the provided report.
        6. NEVER suggest additional problems beyond the supplied findings.
        7. If a rule is not present, assume nothing about it.
        8. Use only the provided score, grade, summary, and issues.

        Your responsibilities are ONLY to:

        - Explain each issue in simple language.
        - Explain why it matters.
        - Suggest a practical fix.
        - Prioritize the issues by impact.

        For every recommendation:

        - Keep the explanation under 80 words.
        - Keep the action plan under 60 words.
        - If HTML code can solve the issue, include a small HTML example.
        - Do not repeat the same explanation multiple times.

        Return ONLY valid JSON.

        Schema:

        {
        "summary": {
            "executiveSummary": "string",
            "overallAssessment": "string"
        },

        "topPriorities": [
            "string"
        ],

        "recommendations": [
            {
            "ruleId": "string",
            "title": "string",
            "whyItMatters": "string",
            "actionPlan": "string",
            "example": "string | null"
            }
        ]
        }

        Here is the SEO report generated by the rule engine.

        ${reportString}

        Remember:

        - Do not invent new issues.
        - Do not invent statistics.
        - Do not mention anything not present in the report.
        - Output ONLY JSON.
    `
    return prompt;
}